---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tinyllama-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux-config/clusters/dev/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
