apiVersion: v1
kind: Service
metadata:
  name: tiny-llama-service
  namespace: vllm-system
  labels:
    app: tiny-llama
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: tiny-llama